// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as yaml from 'js-yaml';
import * as process from 'node:process';

const YAML_CONFIG_FILENAME = `./src/config/${process.env.NODE_ENV}.yaml`;

const url = () => {
  const file = readFileSync(join(__dirname, YAML_CONFIG_FILENAME), 'utf8');
  const config = yaml.load(file) as Record<string, any>;
  return `${config['db'].postgresql}?schema=${config['db'].schema}`;
};

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    url: url() ?? env('DATABASE_URL')
  }
});
