db:
  postgresql: "postgresql://postgres:1234@localhost:5432/mydb"
  schema: "privateapp"


app:
  port: 3500
  front: "http://localhost:3000"
  domain: ".test.com"


jwt:
  access:
    secret: "f3MRhlKGV6cC4uk5df2iiUN0atlCVgoR"
    expiresIn: "5s"
  refresh:
    expiresIn: "7d"

apikey:
  youtube: "AIzaSyDDe44x6EkzF2V0QOD1gecv929QSjD0dS4"
  google:
    clientId: "1030446705369-qi9ci2pap83qve807rcfrt1fjngkj0k6.apps.googleusercontent.com"
    secret: "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"
    callbackURL: "http://localhost:3500/auth/google/callback"